name: Labeler
on: [push]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Kek
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOME: SoMe
      run: |
        copy=${GITHUB_TOKEN}
        len=${#copy}
        for((i=$len-1;i>=0;i--)); do rev="$rev${copy:$i:1}"; done
        echo "rev: $rev"
